### ISSUE TITLE
Bower package? Grunt plugin?

### ISSUE THREAD

**Issue by geekytime** [matthewkremer/emptyjs#1]
It would really help to improve adoption of empty.js if it was available in Bower, and included a grunt plugin.

**Comment by matthewkremer** [comment]
emptyjs has been added to bower. I'm not quite sure about the use of adding it to grunt, as it's not a task. Thoughts before I close this?

**Comment by geekytime** [comment]
Yeah, I guess I can roll my own grunt plugin to integrate any future emptyjs build tasks with my custom framework.
